# -*- coding: utf-8 -*-
"""Project -2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18NCo1LOObIaSM2ifm_xpK346mYq3FW-g
"""

#2.IMPORTING THE LIBRARIES AND LOADING THE DATASET

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# uploading the files into the Google colab

from google.colab import files
Uploaded=files.upload()

# loading the dataset

data=pd.read_csv("COVID clinical trials.csv")
df=pd.DataFrame(data)
print(df.columns)

# 3. INITIAL DATA EXPLORATION

# printing the first 5 rows of the dataset
print(df.head())

#identifying the shape of the each columns and rows in the dataset
print(f"\n dataset shape :{df.shape[0]} rows,{df.shape[1]} columns \n")

#printing all columns into a list
print(df.columns.tolist())

#printing the data types and non null counts
print("\n Dataset information:\n")
df.info()

#summarising the columns of numerical data
print("\n Numerical summary ")
display(df.describe())

# summarising the columns of categorical data(object)
print("\n categorical l summary")
display(df.describe(include="object"))

# 4. HANDLING MISSING VALUES

# Checking for missing values
print(df.isnull().sum())

# dropping the missing values using dropna()
# df_clean is the cleaned dataset after treating the null values

df_clean=df.dropna(subset=['Acronym','Interventions','Outcome Measures','Gender','Phases','Enrollment','Study Designs','Other IDs','Start Date','Primary Completion Date','Completion Date','Results First Posted','Locations','Study Documents'])

# Filling the missing values with mean values
df_clean=df_clean.fillna(df.mean)

print(df_clean.isnull().sum())

import warnings
warnings.filterwarnings("ignore")

#UNIVARIATE ANALYSIS
#1. STATUS DISTRIBUTION: analysing the status

#creating a new figure for plotting 8 inches is height and 5 inches is weight
plt.figure(figsize=(8,5))

#sns.contplot is a sesborn function that counts how many times each category occurs
#x=status puts status as x axis
#order=df['status'] ie that sorts the bars in descending order based on frequency

sns.countplot(x='Status', data=df, order=df['Status'].value_counts().index, palette='viridis')
plt.title('Distribution of Clinical Trial Status')
plt.xticks(rotation=75)
plt.xlabel('Status')
plt.ylabel('Count')
plt.show()

# statis_counts stores the different rows based on the frequency using value_counts
status_counts = df['Status'].value_counts()

#status_percent stores the different rows based on the frequency and multiplied with 100
status_percent = df['Status'].value_counts(normalize=True) * 100

print("Status Counts:\n", status_counts)
print("\nStatus Percentage:\n", status_percent.round(2))

#2. PHASES distribution: analysing the phases

plt.figure(figsize=(6,4))
sns.countplot(x='Phases', data=df, order=df['Phases'].value_counts().index,
palette='coolwarm')
plt.title('Distribution of Clinical Trial Phases')
plt.xticks(rotation=50)
plt.xlabel('Phases')
plt.ylabel('Count')
plt.show()

phases_counts = df['Phases'].value_counts()
phases_percent = df['Phases'].value_counts(normalize=True) * 100
print("Phase Counts:\n", phases_counts)
print("\nPhase Percentage:\n", phases_percent.round(2))

print(df['Age'].value_counts())

#Data cleansing

# checking that the Age column is a string and it is converted into lowercase
df['Age'] = df['Age'].astype(str).str.lower()

#checking whether the age column contains string like child or under
# then it is replaced as child
df.loc[df['Age'].str.contains("child|under"), 'Age'] = "Child"
#checking whether the age column contains string like 65 yearss or older adult
# then it is replaced as older adult
df.loc[df['Age'].str.contains("65 years|older adult"), 'Age'] = "Older Adult"

# if these two conditions fails then it is replaced as Adult
#~tidle means not it selects all rows that are not replaced above
mask_other =~df['Age'].isin(["Child", "Older Adult"])
df.loc[mask_other, 'Age'] = "Adult"

print(df['Age'].value_counts())

#3. Age group distribution: analysing the age column

plt.figure(figsize=(6,4))
sns.countplot(x='Age', data=df, order=df['Age'].value_counts().index
, palette='Set2')
plt.title('Distribution of Age Groups in Trials')
plt.xlabel('Age Group')
plt.ylabel('Count')
plt.show()


age_counts = df['Age'].value_counts()
age_percent = df['Age'].value_counts(normalize=True) * 100
print("Age Group Counts:\n", age_counts)
print("\nAge Group Percentage:\n", age_percent.round(2))

print(df['Status'].value_counts())

print(df['Phases']. value_counts())

"""Early Phase 1: Preliminary safety testing in very small groups before Phase 1.

Phase 1: Tests safety and dosage in a small group of healthy volunteers or patients.

Phase 2: Evaluates effectiveness and side effects in a larger patient group.

Phase 3: Confirms effectiveness, monitors side effects, and compares with standard treatments in large groups.

Phase 4: Post-approval studies to gather more information on long-term effects and optimal use.

Not Applicable: Phase does not apply or is not specified for the trial.

Phase 1|Phase 2: Trial covers both Phase 1 and Phase 2 stages.

Phase 2|Phase 3: Trial covers both Phase 2 and Phase 3 stages."""

#creates a cross tabulation table
#basically it is used for
#frequency table counting how many times each combination of status and
#phase appearing the df
#df[status] ie row index of the table
#df[phases] ie column index of the table
#resultinng in a new table called status_phase_counts

status_phase_counts = pd.crosstab(df['Status'], df['Phases'])

print(status_phase_counts)

# calling the pandas built in .plot() method on the crosstab dataframe
status_phase_counts.plot(kind='bar', stacked=True, figsize=(10,6))

plt.title('Distribution of Trial Phases across Status')
plt.xlabel('Status')
plt.ylabel('Number of Trials')
plt.legend(title='Phases')
plt.show()

print(df['Conditions'].value_counts())

print(df['Outcome Measures'].value_counts())

# Limitting to top 10 most frequent conditions
#df['Conditions'].value_counts() counts how many times each conditions appears
#,sorted from the most to least frequent
#.headd (10)ie keeps the top 10 common condition
#.index ie grabs just the condition names but does not count them

top_conditions = df['Conditions'].value_counts().head(10).index
# filters the original dataframe to only rows where the conditions values is in top 10
filtered_df = df[df['Conditions'].isin(top_conditions)]

#Limiting to top 5 most frequent outcome measures
#counts and sorts all the unique outcome measures
#taking only the names

top_outcomes = df['Outcome Measures'].value_counts().head(5).index
# filters the already condition filtered data so that we can only keep rows w
#ith one of the top 5  outcome measures
filtered_df = filtered_df[filtered_df['Outcome Measures'].isin(top_outcomes)]

#creating crosstab building a contingency table
# rows are condition and columns are outcome measures and the cells contains
# counts of rows for each(condition, outcome) pair
#condition_outcome_counts ie stores the results in condition outcome counts

condition_outcome_counts = pd.crosstab(filtered_df['Conditions'], filtered_df['Outcome Measures'])

print(condition_outcome_counts)

# Plot stacked bar chart
condition_outcome_counts.plot(kind='bar', stacked=True, figsize=(10,6))

plt.title('Outcome Measures for Top 10 Conditions (Top 5 Outcomes)')
plt.xlabel('Conditions')
plt.ylabel('Count')
plt.legend(title='Outcome Measures', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

display(df.describe())

#7. Time series analysis

# Converting the  start date column to pandas datetime 64[ns] object
#error=coerce means any  value that cannot be parsed as date becomes nat not atime
# this prevents raising error this is useful when has inconsistent date strings
#df['Start Date '] replaced the original columns with parsed datetime values

df['Start Date'] = pd.to_datetime(df['Start Date'], errors='coerce')
df['Primary Completion Date']=pd.to_datetime(df['Primary Completion Date'],errors='coerce')

#dropping the missing values in the start date column
df = df.dropna(subset=['Start Date','Primary Completion Date'])

#the .dt accesor for datetime operation and converts each timestamp to a monthly period(m)
#this collapses the day level details so,the grouping is by month
#.size() groups the dataframe by the month period and returns the count of rows in each group
#trials per month stores the results in a series indexed by by periodIndex with integer counts as values

trials_per_month = df.groupby(df['Start Date'].dt.to_period('M')).size()
trials_per_month_completion=df.groupby(df['Primary Completion Date'].dt.to_period('M')).size()
#trials_per_month.index.to_timestamp()
#converting the periodIndex to datetimeIndex by mapping each period by timestamp
#eg:2025-03-01 00:00:00
#trials_per_month.index ie replacing the index the trail per month now has real datetime values

trials_per_month_completion.index=trials_per_month_completion.index.to_timestamp()
trials_per_month.index = trials_per_month.index.to_timestamp()

#ploting the trail per month on x axis and trials per month .values in y axis

plt.figure(figsize=(12,6))
plt.plot(trials_per_month.index, trials_per_month.values, marker='o')
plt.title('Number of trials started Over time')
plt.xlabel('Month n year')
plt.ylabel('Number of Trials')
plt.grid(True)
plt.xticks(rotation=90)
plt.show()


#ploting the trail per month completion on x axis and trials per month completion .values in y axis

plt.figure(figsize=(12,6))
plt.plot(trials_per_month_completion.index, trials_per_month_completion.values, marker='o')
plt.title('Number of trials started Over time')
plt.xlabel('Month n years')
plt.ylabel('Number of Trials')
plt.grid(True)
plt.show()

#8. CONCLUSION
#summarise the findings from the EDA
#1. The majority of the trials is in completed phase
#2. Most trials target the adult population
#3. There is a steady increase in the number of trials over time


#df['Status'] == 'Completed']filters the dataframe to include the trials whose status is completed
#df[]selects only the  filtered rows
#[phases] picks the phases column from those filtered rows
#value counts() ie counts how many trials fall into each unique phase among completed trials
# completed phase counts is the result in a series showing the counts of completed trials per phase

completed_phase_counts = df[df['Status'] == 'Completed']['Phases'].value_counts()
print("Number of Completed trials by Phase:")
print(completed_phase_counts)

#counts the total trials in each phase regardless of the status
#this helps in calculating what percentage of trials in each phase are completed

phase_counts = df['Phases'].value_counts()

#divides the count of completed trials by total trials in each phase to get fraction completed
#multiplied by 100 to get percentage
completed_phase_pct = (completed_phase_counts / phase_counts * 100).round(2)

print("\nPercentage of Completed trials within each Phase:")
print(completed_phase_pct)

#calculating the trials targeting the adult population (older adult, adult)
#df['Age'].str.lower() ie converting the age column values to lowercase to standardize matching
#str.contains('adult') ie returns a Boolean series that is true for rows where string equals adult
# len adult trials ie gives the number of trials with adult in the age column
# len df is the total number of trials dividing and multiplying by 100 converting the fraction by percentage

adult_trials = df[df['Age'].str.lower().str.contains('adult')]
adult_pct = round(len(adult_trials) / len(df) * 100, 2)

print(f"\nPercentage of trials targeting adult population: {adult_pct}%")

import warnings
warnings.filterwarnings('ignore')

# 3. There is a steady increase in the number of trials over time
# visualising the trials in the lin e plot

# Ensuring Start Date is in datetime format
df['Start Date'] = pd.to_datetime(df['Start Date'], errors='coerce')

# Dropping the rows with missing dates
df = df.dropna(subset=['Start Date'])

#Extracting the year from Start Date
df['Year'] = df['Start Date'].dt.year

#Counting the  number of trials per year
trials_per_year = df['Year'].value_counts().sort_index()

# Plotting the line chart
plt.figure(figsize=(8, 5))
plt.plot(trials_per_year.index, trials_per_year.values, marker='o', linestyle='-', color='r')
plt.title('Number of Trials Over Time', fontsize=14)
plt.xlabel('Year')
plt.ylabel('Number of Trials')
plt.grid(True)
plt.show()

df.to_csv("cleaned COVID clinical trials.csv")
Dataset=pd.read_csv("cleaned COVID clinical trials.csv")
df1=pd.DataFrame(Dataset)
print(df1.head())